#!/bin/bash
#SBATCH -J NV
#SBATCH -o qe.%j.out
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH -t 0:01:00
#SBATCH -p pdebug
# SBATCH --dependency=afterany:11446

module load intel impi mkl
NCORES=$(($SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES))
pwdir='/g/g13/smart8/Programs/qe-6.1-default/bin'

srun -n $NCORES $pwdir/pw.x -nk 2 -inp scf.in > scf.out
